### ISSUE TITLE
force transcoding 

### ISSUE THREAD

**Issue by yalagin** [jellyfin/jellyfin-webos#121]
Hi 
I have tv with 60 herz refresh screen when I try to play 60 frames p/s video it's forcing transcoding for me can I bypass it? and stream direct 60 frames instead of converting to 30 frames ?

**Comment by anthonylavado** [comment]
Are you sure it's only transcoding if it's 60fps? What does the playback info in the dashboard say? You can bring that up from a phone/computer while playing the video on the TV.

**Comment by yalagin** [comment]
![IMG_4390 Крупный](https://user-images.githubusercontent.com/12879142/199403508-2ff3aace-0c00-4e4b-8040-88f1b88e9bea.jpeg)

**Comment by yalagin** [comment]
![IMG_4390 Крупный](https://user-images.githubusercontent.com/12879142/199403587-3bc2915b-403c-4b33-946c-da962883d34e.jpeg)

**Comment by yalagin** [comment]
Ah it's not refresh rate it's bitrate =) so my tv accept only 120mbps and higher is transcoded

**Comment by yalagin** [comment]
And one more question when I watch it directly from usb flash card it can be viewed without transcoding. Can I force video to be transmitted without transcoding because I think if my media player on tv plays it nicely, I don't really need to transcode it ?

**Comment by yalagin** [comment]
Ah I got it the current limitation is 4k 120mbps and for now there is no support of higher mbps so I need to wait of supporting 8k transmission or something

**Comment by yalagin** [comment]
ah actually no when I play from the web-browser or the mobile there is no transcoding but for TV it does transcode

**Comment by dmitrylyzo** [comment]
apiclient and jf-web have hardcoded limits.
- 120Mbps
https://github.com/jellyfin/jellyfin-web/blob/6a790a19f8819b42728dbdedf14300913b2b4db7/src/scripts/browserDeviceProfile.js#L258-L260
- 140Mbps for LAN
https://github.com/jellyfin-archive/jellyfin-apiclient-javascript/blob/6e3ace3aac1228870fd85b1af41502c3bb688e6d/src/apiClient.js#L4092-L4097
This will be fixed by https://github.com/jellyfin-archive/jellyfin-apiclient-javascript/pull/424

**Comment by yalagin** [comment]
hi thanks in new version it's working
