### ISSUE TITLE
Version 1.1.2 on LG Store

### ISSUE THREAD

**Issue by supersebbo** [jellyfin/jellyfin-webos#128]
My TV suggested upgrading to version 1.1.2 this morning but I can't see an equivalent release here.  Just wanted to make sure this is legitimate?

**Comment by ajbanck** [comment]
Looks like this is the release for webOS 5.0 as discussed in #99 
It is now available on my 2020 LG tv which did not support 1.1.0

**Comment by anthonylavado** [comment]
Yes this is correct. There are no code changes, which is why I technically haven't cut a new tag yet. The release is safe to use, and is the long awaited webOS 5 update.

It's funny - I had to submit a whole new version number (even with no code changes) for them to just click the checkbox that allows it on a different OS.

**Comment by Hallo951** [comment]
Oh wonderful...thank you so much... Now I can finally switch off this stupid dev mode and the app is finally permanently installed on my TV... Wonderful

Now just fix the last bugs and everything is wonderful...

**Comment by hmonteiro** [comment]
Does it rollout to other regions automatically?

**Comment by hmonteiro** [comment]
Ignore my question, just realised that I'm on webos 4. Looks like I'll have to continue relying on the development version. Do you have plans to make it available for web os 4 in the store at some point?

**Comment by anthonylavado** [comment]
@hmonteiro Yes, we plan to target all versions.

**Comment by etu** [comment]
@anthonylavado I have my region set to the country of where I live (Sweden). And I have the app installed from the content store using the developer mode on a WebOS 5.

However, I tried to go into the store to give it a rating and click on the app and it told me that the app isn't available in my country. Is there any plans to open up for more countries?

**Comment by etu** [comment]
@anthonylavado I am, because before it was announced that it was released to webOS 5 I couldn't find it in the store at all.

Following 2. from @ajbanck here:
- Model: OLED55CX6LA
- webOS TV Version: 5.4.1-15 (jhericurl-jebil)

Bought new in May 2021.

Settings > General > Location:
- Broadcast Country: Sweden
- Service Area Postcode: Filled out
- LG Services Country: Sweden

Worth to note, I don't have a VPN for my home network, however it's common that if I approve webpages to use my location I often end up in Germany... since a while back. I guess my IP is wrong in some geolocation databases.

This is what I get when I go to LG Content Store > My Apps and press Jellyfin:
![IMG_20221212_211823](https://user-images.githubusercontent.com/461970/207146188-1260431c-8a96-4e42-9423-c5c9ea801903.jpg)

**Comment by ajbanck** [comment]
Jellyfin in the screenshot is missing the installation date. If the app was installed in developer mode and/or from another channel likely the installed app ID doesn't match the app ID in the store. You can search for 'Jellyfin' in the store and see if it is found.
If you feel there is an issue please best to create a new issue as this shouldn't be discussed in a closed different issue thread

**Comment by etu** [comment]
Right, you're entirely correct. Uninstalled and installed from the store. Dev mode disabled and it works great. Also left a 5/5 :star:  rating in the store :slightly_smiling_face:

**Comment by dvoina** [comment]
I have a LG 49SK7900PLA tv running WebOS 06.10.30. 
I couldn't see Jellyfin in any of European LG content stores.

**Comment by anthonylavado** [comment]
@dvoina I hate to break it to you, but that looks like a "Software Version", not a "webOS Version". webOS is locked and set when you buy the TV, and is not upgradable. For whatever reason, LG buries the webOS version deeper in the settings, but it's in there. It can also be found by looking up your TV specifications.

In this case, your Tv appear to be webOS 3.5.

**Comment by dvoina** [comment]
@anthonylavado: No worries and thanks. At least I won't spend days figuring out things.
