### ISSUE TITLE
Audio issues with JellyFin WebOS client on LG CX OLED & Sonos ARC (2 channel AAC or no audio)

### ISSUE THREAD

**Issue by classicjazz** [jellyfin/jellyfin-webos#129]
I am testing the newly released JellyFin WebOS 5.0 client on my LG CX OLED TVs with Sonos ARC soundbar + Sonos Ones and SUB. The Sonos ARC is connected via EARC using HDMI 2.1 48 Gpbs cables.

Video renders extremely well. But audio is either 2 channel AAC (when transcoding DTS variant codecs) or inaudible (TrueHD), notwithstanding that the JellyFin server status states that it is direct playing: _"The source file is entirely compatible with this client, and the session is receiving the file without modifications."_

I don't know where to look for the client profile used by the WebOS client. My understanding from other issues is that it is different than the LG TV DLNA client profile and is not user over-ridable using an XML profile (like JellyFin DLNA profiles or Plex client profiles).

In an ideal world, I would create a client profile that translates any unsupported audio codec that can't be either decoded by the LG TV or passed through as a bitstream to the Sonos ARC to FLAC format (at the cost of losing Atmos objects). Researching this further, however, it appears  that the LG Alpha9 SOC does not support lossless audio from WebOS applications: _"there will be no WebOS app support for lossless HD audio soundtracks such as TrueHD, TrueHD+Atmos, DTS-HD HR, DTS-HD MA or DTS:X"._ Due to the ARC protocol (not Sonos ARC) bandwidth constraints, I assume that this also applies to FLAC but can't confirm that. 

https://www.avsforum.com/threads/2020-lg-oled-cx-gx-owners-thread-faq-posts-1-6-no-price-talk.3119288/

Assuming that this is true, then the next best thing would be for the JellyFin server to transcode all audio codecs to EAC3 with a 960Kbps ceiling to comply with the ARC protocol. If I were configuring FFMPEG to transcode from the MacOS Terminal, then the relevant audio configuration would be something like: 
`-c:a:0 eac3 -b:a:0 960k`

My questions are:
1.) Are my baseline assumptions about LG CX + Sonos ARC including lossless audio accurate?
2.) How can I transcode all audio (other than DTS core and DD) to EAC3 (DD+) in JellyFin?
3.) Does #2 require modifications to the underlying JellyFin code or is it user over-ridable?

**Comment by ajbanck** [comment]
Currently the client device profile is build in code and can't be overridden. For the WebOS app the profile is for the most part set in the [jellyfin-web](https://github.com/jellyfin/jellyfin-web) app. The [WebOS app](https://github.com/jellyfin/jellyfin-webos/) is a thin wrapper around this which also sets some properties used to build the device profile.

You are likely experiencing different issues. Looks like TrueHD is incorrectly set as supported as it's enabled in code when Atmos support is detected. See the code [here in webOS.js](https://github.com/jellyfin/jellyfin-webos/blob/master/frontend/js/webOS.js#L82).
AFAIK [DTS should always be transcoded](https://github.com/jellyfin/jellyfin-web/blob/master/src/scripts/browserDeviceProfile.js#L441) on the CX. Are you running a recent version of Jellyfin?

The description of why TrueHD lossless is not supported for WebOS apps is a bit ambiguous. The inability to play lossless audio from apps running on WebOS are not caused by ARC or the ARC protocol but with the soc and/or the WebOS implementation not supporting this. I didn't find documenation of a bandwith cap. An Sonos Arc can play TrueHD audio when connected to the LG CX by HDMI/EARC using passthrough, for example Jellyfin on a Nvidia Shield.
