### ISSUE TITLE
Jellyfin WebOS app on Homebrew channel

### ISSUE THREAD

**Issue by jimlynnjulian** [jellyfin/jellyfin-webos#134]

**Comment by anthonylavado** [comment]
@jimlynnjulian First thing - that looks like your LG tv "software version", which is not the same as "webOS Version". There should be a way to find out your actual webOS version somewhere in the menu, or by looking up the specifications from your model TV.

For the other points, it's currently available worldwide for webOS 5 and webOS 6. This is all TVs from (March) 2020, 2021, and 2022+. For older TVs, there are four options:

1. Install the app with Developer Mode, and use scripts/options to keep it active instead of expiring after 48h.

2. Use another method to install (like rooting).

3. Use the built in browser with your Jellyfin server.

4. Wait for further releases (we are trying to get at least as far back as webOS 3.5 or so, which would be TVs from late 2016 onwards).

**Comment by jimlynnjulian** [comment]
I found the WebOS version data in the 'about' section.
4.4.2-10 (goldilocks-gorongosa)

1. The dev mode approach is a nuisance.

2. I examined the 'rooting' approach but found the Homebrew/rootmy.tv approach lacked coordination with jellyfin.org. In short, seems risky. Besides, someone mentioned Homebrew uses 1.1.0 of the Jellyfin webos app at
https://github.com/jellyfin/jellyfin-webos/releases/tag/v1.1.0

3. I've been using the tv browser and...

4. ...awaiting the future.
