### ISSUE TITLE
DTS audio not working

### ISSUE THREAD

**Issue by MrHumanRebel** [jellyfin/jellyfin-webos#190]
Hi!

Whenever I play any movie with DTS surround sound there is no sound at all on my TV. 

Thanks in advance.

**Comment by anthonylavado** [comment]
What model TV are you using?

**Comment by MrHumanRebel** [comment]
55c21la

**Comment by Cyberbeni** [comment]
I also had to add `supportsDts: false` here: https://github.com/jellyfin/jellyfin-webos/blob/3cf2c835fed6017bbe61ea81ad962ed1827c0d0d/frontend/js/webOS.js#L81

I have a 32LM6300PLA

**Comment by dmitrylyzo** [comment]
> I have a 32LM6300PLA

It supports DTS. https://www.lg.com/uk/tvs-soundbars/smart-tvs/32lm6300pla/
The question is, does it support 5.1?

**Comment by sundermann** [comment]
Technically, the fix done in https://github.com/jellyfin/jellyfin-web/pull/5053 is not correct because only select 2023+ webOS TVs support dts. It will also cause trouble on the TVs that were upgraded from webOS 22 to 23 using the new webOS renew program. Those TVs don't support dts but will still report webOS 23 as version. I strongly suggest reverting the patch in jellyfin-web and instead use the luna bus to query for dts support:

```bash
luna-send -n 1 -f luna://com.webos.service.config/getConfigs '{"configNames": ["tv.model.edidType"]}'
{
    "subscribed": false,
    "configs": {
        "tv.model.edidType": "TrueHD+dts"
    },
    "returnValue": true
}
```

**Comment by radry** [comment]
> Technically, the fix done in [jellyfin/jellyfin-web#5053](https://github.com/jellyfin/jellyfin-web/pull/5053) is not correct because only select 2023+ webOS TVs support dts. 

My 2019 OLED model also supports DTS (webos 4.5) LG dropped DTS support only for 2020-2022 models.

**Comment by dmitrylyzo** [comment]
@sundermann Thanks for the info. That change may be kept because the app can pass `supportsDts` with the correct value, which is prioritized. Could you open a PR in this repo with the changes you mentioned?

It would also be interesting to test DTS on a TV with webOS 22 upgraded to 23.

**Comment by sundermann** [comment]
@dmitrylyzo I don't really feel confident enough in JS stuff to make these changes. I just came across this issue randomly while working on the kodi webOS implementation. I did look into how LG's apps are detecting dts support and thus shared the information here.

I'd still strongly recommend reverting https://github.com/jellyfin/jellyfin-web/pull/5053 because jellyfin 10.9 is going to release very soon and users will receive the new dts bandaid fix. This is going to break any dts audio on 2022 TVs. Whilst it's true the dts support can be overwritten in jellyfin-webos, it's very unrealistic to have another release on the LG app store before jellyfin 10.9 is released.

**Comment by sundermann** [comment]
Another thing that came into my mind is that LG only allowed DTS passthrough until webOS 5. Meaning that it only works if you had an external device attached via ARC. Not sure what the luna call above is returning in that case. I might be wrong about this detail though (I have webOS 22 😅 ) Supported webOS 23+ devices on which the above luna call returns dts support can both passthrough and also output dts via internal speakers.

**Comment by hexoverflow** [comment]
I have a webOS 22 TV (LG G2) and recently updated it to webOS 23. Jellyfin was working fine with dts files. Since I've updated my server to 10.9 unstable I don't have audio for dts files anymore.

**Comment by dmitrylyzo** [comment]
PR https://github.com/jellyfin/jellyfin-webos/pull/221 needs testing.
Since this will probably only work on webOS 23+, the DTS "detection" for webOS 23 in jellyfin-web should be removed.
