### ISSUE TITLE
Black screen instead of login

### ISSUE THREAD

**Issue by 1024mb** [jellyfin/jellyfin-webos#22]
I have installed the ipk (building it from CLI) from the IDE on the LG TV but after entering my IP and port all I got is a black screen, there is one issue like this but it was closed without a proper fix.

Is there something one must do to get this working? First time installing it on the TV.

**Comment by 1024mb** [comment]
The problem is the latest version of Jellyfin, and by latest I mean built from source yesterday. Is probably the same problem it has with Yatse. Installed 10.5.5 and it works well but I would like to use the latest fixes.

**Comment by StefanAbl** [comment]
I also had this problem, for me it turned out to be to be an issue with my nginx reverse proxy. It didn't allow embedding in an iFrame which the WebOS app does. I commented out  `add_header X-Frame-Options SAMEORIGIN;` and ` #add_header Content-Security-Policy ...` Maybe there is a way to allow the WebOS app in the Content-Security-Policy.

**Comment by MasterCATZ** [comment]
I have just installed what ever version ubuntu 20.04 supplies and it is doing this also Jellyfin.Server 10.6.4.0
