### ISSUE TITLE
preferred transcode audio codec setting FLAC not working

### ISSUE THREAD

**Issue by 24fpsDaVinci** [jellyfin/jellyfin-webos#234]
when setting Preferred transcode audio codec to FLAC, the track is instead transcoded to AAC. 

Other options like OPUS work as intended.

**Comment by dmitrylyzo** [comment]
How many audio channels?

**Comment by 24fpsDaVinci** [comment]
6 channels

**Comment by dmitrylyzo** [comment]
> 6 channels

Since FLAC with more than 2 audio channels is not well supported in webOS (https://github.com/jellyfin/jellyfin-webos/issues/146), it has been limited to 2 channels for video (https://github.com/jellyfin/jellyfin-web/pull/5452). In your case it means that Jellyfin selects the next supported codec to support 6 audio channels - AAC.

**Comment by 24fpsDaVinci** [comment]
Ok, looks like they chose to preserve channels with AAC instead of downmixing. thank you
