### ISSUE TITLE
Selected subtitle is not played/shown

### ISSUE THREAD

**Issue by 1024mb** [jellyfin/jellyfin-webos#31]
When a video is played and a subtitle is selected the player doesn't show it (or load it? Idk), one has to choose another subtitle and then choose back the preferred subtitle again. I have only tested this with SRT subs.

Jellyfin server is 10.6.2.

**Comment by naku** [comment]
Same issue here. I usually choose "no subtitles", then start the video, then select the subtitle.

Also for some reason the subtitles don't show up after about 10 seconds

**Comment by oddstr13** [comment]
I see I have this in my notes from testing against 10.6, but I had subs when testing with 10.7.

Are you able to test and verify this against 10.7?

**Comment by anthonylavado** [comment]
Closing for now. Please reopen if this still persists in 10.7, with details about the subtitle format used :-)

**Comment by lorentzkim** [comment]
> Same issue here. I usually choose "no subtitles", then start the video, then select the subtitle.
> 
> Also for some reason the subtitles don't show up after about 10 seconds

Issue still persists for me (jellyfin server is on 10.8 alpha5, jellyfin-webos is on whatever's in homebrew channel).

What I _think_ is happening is the stream always requests for subtitle to be extracted from the media from the server, rather than stream the subs from the file directly as you watch it. It's especially true for me because my file server is particularly slow (basically cloud storage), and extraction of subtitle always fails for me because it takes as long as it takes to download the whole video. My understanding is that subtitles are scattered all over the file, not just in the header or footer, thus takes time.

I can prove it's slow doing the subtitle extraction when I run something like `/usr/lib/jellyfin-ffmpeg/ffmpeg -i /movies/some-long-bluray-vid.mkv subtitle.srt`. Takes forever. I also get log entries in server log telling me:

```
jellyfin    | [11:28:27] [WRN] [75] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Killing ffmpeg subtitle extraction process
jellyfin    | [11:28:27] [WRN] [75] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Deleting extracted subtitle due to failure: /config/data/subtitles/9/9d5b9c33-17f7-2ad7-a2b5-efbcb3390608.srt
jellyfin    | [11:28:27] [ERR] [75] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/movies/some-long-bluray-vid.mkv" to /config/data/subtitles/9/9d5b9c33-17f7-2ad7-a2b5-efbcb3390608.srt
```

It probably wouldn't be a big deal if the files were truly local and the subs can be extracted in <30s, but it's not possible for me as is.

Is it not possible to tell the server to just send the subtitles directly during watching, rather than extract it first?

**Comment by Informatic** [comment]
I noticed this as well when "Direct playing" on Jellyfin 10.7.7 on webOS 3.8.

On webOS (at least 3.8) subtitles in mkv files are not rendered, unless a call to an undocumented `com.webos.media` Luna (public) service is made.

`HTMLVideoElement` contains a non-standard/undocumented `mediaId` string attribute which contains internal media pipeline identifier.
It then needs to be passed to `luna://com.webos.media/setEnableSubtitles` `{"mediaId": "...","enable": true}` call. Some extra methods are exposed for switching active track and customizing subtitles font/color/sizing.

Following snippet executed in Developer Toolbar console of a TV running Jellyfin shows subtitles properly with direct streaming:
```js
webOS.service.request("luna://com.webos.media", { method: "setSubtitleEnable", parameters: { mediaId: document.querySelector('iframe').contentWindow.document.querySelector('video').mediaId, enable: true }})
```
Subtitles are rendered properly afterwards:
![capture](https://user-images.githubusercontent.com/1131102/162804898-cbbfb12a-0c16-4583-a4a3-4632a8e51ce5.png)

None of these APIs are documented publicly yet, but I can try writing up some docs about this on https://webosbrew.org and try integrating this into jellyfin-web, if this is actually considered useful. (I have no idea how subtitles extraction/rendering works in jellyfin/jellyfin-web itself, and if this is *actually* necessary)

Note - even though this is not documented publicly anywhere, certain third party apps on LG Content Store are already using these calls.

**Comment by dmitrylyzo** [comment]
I know about that `const`, but `subtitles-octopus.js` was transpiled before, iirc, and was embedded to other module (main or htmlVideoPlayer). Maybe that was a bug of webpack (run babel on it) or I just wasn't looking hard enough.

It works as is in the webOS 1.2 emulator because the WebKit engine probably doesn't parse code at once, and that block is wrapped with `try/catch`.

webOS 3 is the first to use the Chrome engine, and it has a glitchy emulator, so I rarely test on it. It looks like the Chrome engine parses whole code, so it requires libass to be transpiled.

**Comment by letshin** [comment]
I installed Jellyfin on WebOS 3.5, and have the same issue with ASS subtitles not showing up. If I set the subtitles to be hardcoded to "Always" the video no longer runs as it says the format isn't supported.
