### ISSUE TITLE
[bug] Hamburger menu doesn't work [WebOS 6, server 10.5.5]

### ISSUE THREAD

**Issue by dovecode** [jellyfin/jellyfin-webos#49]
Client: LG WebOS 06.00.05
App version: built from commit a05bc39, installed with CLI
Server version: 10.5.5
Server OS: Ubuntu

The UI has a hamburger menu in the top-left, but it appears to be non-functional. When clicked the entire UI dims slightly as though a pop-up should appear, but nothing else happens.

**Comment by anthonylavado** [comment]
Because you're using 10.5.5, this might now be a fixed issue. My understanding is that a lot of the work to make this usable went in to the 10.7.x releases. 

The app for the TV is essentially a specialized web viewer to load what's on your server. Since the versions of Jellyfin-Web are tied to your server install, this means that you need to be running the latest release to have all the fixes.

On the plus side, once the app gets approved, it means we can update the experience without having to ship a new version to LG all the time. On the downside, fixes mean that the Jellyfin-Web (and thus the server) need to be released with an update.

**Comment by dovecode** [comment]
Hmm... I thought I was on the latest version (an `apt update` didn't show any available updates). Looks like a recent OS upgrade had disabled my jellyfin repo (thanks, Ubuntu!).

Now I upgraded and the hamburger menu disappeared. I suppose that's one way of fixing that :)

On a related note: I also lost my ability to manage the server from my user profile menu after upgrading the server -- there's no longer a Server Dashboard menu item. Before I go ahead and open another issue on that: is that expected behavior?

**Comment by anthonylavado** [comment]
@dovecode Yes, that's expected behaviour. My understanding is that the team couldn't create a "good" dashboard layout for the TV display, that also worked with plugins.

**Comment by dovecode** [comment]
OK, thanks. I'm closing this issue.
