### ISSUE TITLE
Release For Testing

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-webos#50]
Hey all,
Here's the release we're using for testing. It's also available on our [repo](https://repo.jellyfin.org/releases/other/org.jellyfin.webos_1.0.0_all.ipk).
[org.jellyfin.webos_1.0.0_all.ipk.zip](https://github.com/jellyfin/jellyfin-webos/files/6328411/org.jellyfin.webos_1.0.0_all.ipk.zip)

**Comment by agrisci** [comment]
Hello @anthonylavado,
Just tested the ipk on a v.3 emulator and still getting the same error "Unknown error occured..." when trying to connect. Did not get the error on v.4 or v.5 emulator or when tried to connect on my own Jellyfin server v.10.7.2.

**Comment by anthonylavado** [comment]
@agrisci Thanks for the test. I'll install the same emulators and try to debug further. Thanks!

**Comment by agrisci** [comment]
@anthonylavado I think i have narrowed the problem down to something that has to do with https-ssl because i'm getting "err_ssl_protocol_error" in the debug console.
![Screenshot (66)](https://user-images.githubusercontent.com/46535877/115117427-2ab82c80-9fa7-11eb-9fcf-13aca5a8545f.png)
 I don't currently have an https jellyfin server to test it in order to narrow it futher more if it's a server side or client side bug. I will be looking into it more in the coming days.

Also i just wanted to thank you for you really precious contribution in the project!!!

**Comment by anthonylavado** [comment]
Thank you! We're gonna look at this.

**Comment by JulioNahum** [comment]
Install the WEBos Emulator and install jellyfin there. And it worked very well for me. I have a recorded video showing how both the login and the others were. I have a reverse proxy in windows using CADDY and I enter the best. I hope I have contributed something with this message

**Comment by g-a-c** [comment]
> I don't currently have an https jellyfin server to test it in order to narrow it futher more if it's a server side or client side bug

I imagine that rather than being a bug on either side, it's simply age-related. The Jellyfin demo server appears to run TLSv1.2 only, I don't know how old webOS v3/v3.5 are, but I bet they're just too old to support it, at least in some implementations on some models. If someone tweaked the demo server SSL configuration to allow TLSv1.1, I imagine the app would work just fine.

**Comment by khannover** [comment]
According to this table from the [webOS Developer Page](https://webostv.developer.lge.com/discover/specifications/web-engine/) TLS 1.2 is supported by all webOS TV Versions:
![image](https://user-images.githubusercontent.com/4188676/115143796-b387a480-a049-11eb-88f7-422b3f25ccf7.png)

**Comment by anthonylavado** [comment]
Yeah, we saw this in the table and made sure (there's been a bunch of work behind the scenes).

From some more cursory searching on the internet, it seems that the app interface doesn't like Let's Encrypt certificates for some reason, even though the regular browser is okay with it.

**Comment by anthonylavado** [comment]
Before I forget, this conversation should really be continued in #43.

**Comment by marine1988** [comment]
Any uipodates on thsi being published on store?

**Comment by Jakethesnkae** [comment]
Hey there had a question how is the progress on this, didn't want to to be annoying also I appreciate all the work that has been done with the project!

**Comment by anthonylavado** [comment]
This has been superseded by the latest GitHub release, plus the availability on webOS Brew.

You can see #67 and #69 for details.
