### ISSUE TITLE
Jellyfin only shows cuts the picture on tvs edge

### ISSUE THREAD

**Issue by peterge1998** [jellyfin/jellyfin-webos#75]
I installed the 1.01 Release yesterday and noticed this behaviour when scrolling through my library:
![IMG_20220121_093625015](https://user-images.githubusercontent.com/47355238/150504566-74f260ed-85df-484e-a276-b6f3d2bcbd99.jpg)
This pic is taken after i scolled down on the default page. It seems to be cut after the first screen loads, on the tv borders.
I am running webos 6.2.0-23 and the latest 10.7.x as server.

**Comment by anthonylavado** [comment]
Sorry for the late response. Are you using a skin or custom CSS?

We don't test against those and it's possible that they don't handle the TV layout properly.

**Comment by peterge1998** [comment]
Yes. Using custom css...
Any plans to respect it?

**Comment by anthonylavado** [comment]
The issue lies with the custom CSS maker to test their changes with the TV layout.

When you use the webOS app, it's loading the web interface exactly like you would see on the computer - so it's not that we're doing anything different. When we detect that the screen size is a TV, we change from the regular desktop layout to the TV layout, which makes the cards bigger and adapts the controls to make navigation easier.

The best thing here then is if you can talk with the person who made the custom CSS and ask if they can test it on the TV layout. Depending on the changes they've made, they might have success, or they might not. LG TVs (even new ones) usually use very, very old versions of browsers (usually based off of Chrome), and these never get engine updates. So it _could_ be difficult.

On the computer, you can manually switch to the TV layout by going to the user settings.

The steps:
- Open the web interface, click on the user icon at the top right
- Choose Display, and change the Display Mode from Auto to TV
- Scroll down and click Save, and reload the web page

**Comment by anthonylavado** [comment]
What skin is this? Apparently we had tried fixing scrolling once before (because it became an issue on other screens), but it ended up happening again.

**Comment by peterge1998** [comment]
> What skin is this? Apparently we had tried fixing scrolling once before (because it became an issue on other screens), but it ended up happening again.

Its this jellyskin skin: https://github.com/prayag17/JellySkin in an old version. But i should upgrade it, i am just hosting the css files myself to not have external requests.

**Comment by anthonylavado** [comment]
Yeah, it seems there was a fox at least for Tizen TVs, which also use the TV layout: https://github.com/prayag17/JellySkin/issues/49

If your copy is older than December 23 2021, then it may not have this fix. Definitely try updating it and see if it persists.

**Comment by peterge1998** [comment]
> Yeah, it seems there was a fox at least for Tizen TVs, which also use the TV layout: [prayag17/JellySkin#49](https://github.com/prayag17/JellySkin/issues/49)
> 
> If your copy is older than December 23 2021, then it may not have this fix. Definitely try updating it and see if it persists.

Okay, sorry for annoying, after updating the CSS files the issue is gone. Don't know if that PR fixed it, but thank you very much for taking care of this problem which is not even related to jellyfin-webos at all <3
