### ISSUE TITLE
Store version uses anonymous profile instead of LG Profile

### ISSUE THREAD

**Issue by lanwin** [jellyfin/jellyfin-webos#91]
Hi, ive installed the fresh published store version and noticed that all my videos are getting transcoded even if the TV can directly play them. From the logs I can see that each video uses the "anonymous profile" instead of the "LG Profile" witch steam started via DLNA getting used. 

I also can not forward videos are change position (witch never worked for me when transcoding is used).

Device: LG 65G1

**Comment by drujd** [comment]
The app does not utilize DLNA (and therefore profiles) at all, or am I wrong?


I am running the app with DLNA disabled...

**Comment by lanwin** [comment]
Hmm ok I thought it would be. Then the question is, thy does Jellyfin
transcodes my files even when the device can play them natively and how to
disable that.

**Comment by anthonylavado** [comment]
When a video is transcoding, it will list information on the dashboard as to the reason why. If you log in from another device (like a phone or computer) while playing something on the TV, could you let us know what it says the reason is?

Some extra info such as the original codecs (video and audio) will also help us track down what's happening.

Also - to be clear since I think a commenter is deleted/missing, the app does not use DLNA. It should just list it early as a client on the dashboard, there should be no mention of it using any DLNA profiles.

**Comment by anthonylavado** [comment]
Closing for no response…

**Comment by lanwin** [comment]
Ah sorry I totally missed your reply. 

Currently I have not much time to use Jellyfin. But the one time I did, it seemed to work. I upgraded the Backend in the time frame. Maybe that has something todo with it. 

When I have more time again I will report back if I still see that problem.
