### ISSUE TITLE
Jellyfin for WebOS 5

### ISSUE THREAD

**Issue by lexcorp** [jellyfin/jellyfin-webos#99]
On the official website of Jellyfin it mentions the following:

[https://jellyfin.org/posts/webos-july2022/
](url)
What’s Next?

We hope to bring this to more versions of webOS soon. There is one small bug to fix for webOS 5.x, and then we can resubmit with that update. Since the main QA testing work has been performed by LG, this process should be much faster. As time goes on, more enhancements and fixes will follow.

_**Which bugs are you referring to? Maybe I could help in some way.**_

**Comment by anthonylavado** [comment]
I mention it in my Reddit comment: https://reddit.com/r/jellyfin/comments/vurxw4/_/ifhamdw/?context=1

It's related to #46 but not quite the same. I think it's that LG thought any position should be resumable, when right now I have the minimum percentage set to 5 percent of item length.

**Comment by lexcorp** [comment]
Screen LG 32" HD Smart TV LED 32LM630BPUB AI ThinQ
I'm using Firmware: 05.25.35,
Jellyfin WebOS 1.1.0 Installed  vía Developer mode and DevMode Manager for webOS TV:

https://github.com/webosbrew/dev-manager-desktop

I have a server running Jellyfin 10.8.1

**Comment by yairp03** [comment]
Why there isn't an open issue for the problem?

**Comment by dustingrady** [comment]
Any updates on this? :)

**Comment by teijiIshida** [comment]
I tried Jellyfin the other day because I wanted to get away from Emby. Unfortunately, I had to go back to Emby because there was no Jellyfin client for my LG CX TV. Please release a client for this tv. Thanks.

**Comment by zguithues** [comment]
> I tried Jellyfin the other day because I wanted to get away from Emby. Unfortunately, I had to go back to Emby because there was no Jellyfin client for my LG CX TV. Please release a client for this tv. Thanks.

check out rootmy dot tv.

If your tv is not a 2021, you can probably mod it, then install jellyfin from the homebrew store.  i've got a 2020 model tv with webos 5 and the hack works super well.  you don't have to do the developer mode thing, or compile anything.  I hope someday they're able to get the app approved for older versions, so we don't have to do this workaround.

If this discussion is not allowed, please delete my message and i am sorry.

**Comment by anthonylavado** [comment]
Currently awaiting LG's review.

**Comment by kubo6472** [comment]
> ...jellyfin is also installable from the lg homebrew store as a permanent install method on rooted TVs. The rootmy dot tv website...

@iMartyn just want to let you know that 2.0 doesn't work on most webOS 5.x TVs, about whose this thread was started in the first place. I'll be patiently waiting for RMTV 3.0 or this app beung compatible with WOS 5.x whichever comes first. Thanks for trying to get this working for us guys.

**Comment by lexcorp** [comment]
The Jellyfiin team submitted the app for LG to review, which is a process that can take weeks or even months.

@anthonylavado, in your experience, how long does this process take?

**Comment by anthonylavado** [comment]
I recently answered this on Reddit, so I'll post my answer here too:

>No, unfortunately. Some vendors (like Amazon) provide a review time guarantee (which they often miss), while others don’t (like LG).
>
>All through 2020 they had a note that it could take about a month for tests to go through, but that was later removed. Now the only issues would be any Korean holidays, but the most recent one already passed.
>
>Last time it took them about a week and a half, so we’ll just have to wait and see.
>
>**EDIT:** That’s also assuming there are no issues and it is approved. Otherwise it’s back to the drawing board.

**Comment by lexcorp** [comment]
Thank you very much for your time Anthony and for the effort of the Jellyfin team to make this happen.

**Comment by lexcorp** [comment]
> I recently answered this on Reddit, so I'll post my answer here too:
> 
> > Q: Do you know how long it will take until it will available in LG APP store?
> 
> > A: No, unfortunately. Some vendors (like Amazon) provide a review time guarantee (which they often miss), while others don’t (like LG).
> > All through 2020 they had a note that it could take about a month for tests to go through, but that was later removed. Now the only issues would be any Korean holidays, but the most recent one already passed.
> > Last time it took them about a week and a half, so we’ll just have to wait and see.
> > **EDIT:** That’s also assuming there are no issues and it is approved. Otherwise it’s back to the drawing board.

Thank you very much for your time Anthony and for the effort of the Jellyfin team to make this happen.

**Comment by anthonylavado** [comment]
Update - small setback from QA at LG. Making the necessary fix and submitting again later today.

**Comment by lexcorp** [comment]
Thanks for the update! @anthonylavado

**Comment by anthonylavado** [comment]
Don't want anyone to think I forgot about this. I see that LG has tested _something_, but otherwise there has been no change in the Seller Lounge portal. It still says "QA Processing".

**Comment by brettswift** [comment]
Brand new to jellyfin and the LG store approval. 

Maybe for everyone's benefit as well - the post about approval times was helpful but I didn't see anything about how long it goes from QA complete to Published in the store.  Is that because it's immediate? Or is there another time frame for that?

**Comment by anthonylavado** [comment]
All app stores give you three options:
- scheduled release
- manual release
- automatic release

We have all of them set to automatic release, so once it does go through, there's nothing that we need to do. We just let it get pushed through. Of course there's always a delay as they have to push it to their store caches all around the world.

**Comment by ag14774** [comment]
Most responsive dev ever. Thank you

**Comment by iwatch-x** [comment]
@anthonylavado so its published in the us store of lg web os 5 or ?

**Comment by anthonylavado** [comment]
@iwatch-x No, not yet. LG is still reviewing on it. They do not provide timelines or estimates - when they're done reviewing, we get a report whether it was successful or not. If it was successful, it goes out to the LG Content Store worldwide. If it fails review, then we get a report telling us what went wrong, so we can fix it.

Believe me, when I get any news, good or bad, I'll be updating this thread. Otherwise, patience is required 🙂

**Comment by lexcorp** [comment]
Son muy detallistas con las pruebas de aseguramiento de la calidad estos coreanos... :)

**Comment by Wulf-Steppen** [comment]
Big fan of your work and even bigger of your engagement with the community. Thank you for the status updates anthony

**Comment by tyhawk** [comment]
@anthonylavado  Thanks for keeping us updated. I am probably not the only one hoping to remove the Plex app from my TV and installing the Jellyfin app. Would also save me one podman container in my homelab (PMS). :-)

The hard work of the entire team is greatly appreciated!

**Comment by lexcorp** [comment]
![BDB58384-85BB-4256-B724-A6830DFACE3F](https://user-images.githubusercontent.com/5751288/197918775-80c61c05-18a5-4bdd-a100-4fe7b80dbe61.png)
Please rate application no LG content store with five stars 😃

https://us.lgappstv.com/main/tvapp/detail?appId=1030579

**Comment by BenzLeung** [comment]
> ![BDB58384-85BB-4256-B724-A6830DFACE3F](https://user-images.githubusercontent.com/5751288/197918775-80c61c05-18a5-4bdd-a100-4fe7b80dbe61.png) Please rate application on LG content store with five stars 😃
> 
> https://us.lgappstv.com/main/tvapp/detail?appId=1030579

![图片](https://user-images.githubusercontent.com/2764768/197927065-47b1704a-43be-4811-bde2-efb189fa6daa.png)

**Comment by anthonylavado** [comment]
Alright, I appreciate the enthusiasm, but this notifies a whole lot of people with messages we don't need at the moment. I'll be locking further messages until there is something significant to report. It's nothing personal, but we need to protect inboxes here.

**My current status update:**
It's still with LG. There has been no communication back as of yet. It hasn't been approved, but most importantly, it hasn't been rejected either. They seem to keep logging in every few days (see below), play demo media, stop, try again, and then disconnect. I can only assume that they're really going through it. When we last got a set of results, I was honestly staggered by how many devices they tested against. They really go through _everything_.

I'll let you know when the status changes. If it hits 30 days and nothing has moved, I'll send a support request to them for an update.

Regarding store listings, while I appreciate the stars, it doesn't affect anything on their side. It's fine. For webOS 5, it's a compatibility update to the listing, so that same link will be the one to install it for the the TV. One app for all versions is the goal - we don't intend to split it up.

Anyway, I'll let you know if anything changes, and if not, I'll check back in a week's time.

![B95F9122-44B2-4309-89F6-3E1EF04BE598](https://user-images.githubusercontent.com/596194/198135682-1bb2fec0-745f-45b5-9495-df96ecb67ff5.jpeg)

![8E50DE79-D567-487B-9BF4-AF016845E8E3](https://user-images.githubusercontent.com/596194/198136859-ee17c652-e833-4859-9b81-8bf6a06179de.jpeg)

**Comment by anthonylavado** [comment]
Hey folks, checking in here.

My last update was on the 26th, and I decided to check back in a little earlier than usual. On the 28th there was an update posted to LG's Seller Lounge, acknowledging delays in review. I just read this now, so I figured I'd mention it.

Their post is here: http://seller.lgappstv.com/seller/support/retrieveNoticeInfo.lge?seqNo=7236

The message in full:

>Dear Sellers,
> 
>This is LG Seller Lounge.
We deeply apologize for the delay in the App QA process.
> 
>Recently, due to the preparations for next year’s new platform launch and rise in the volume of apps submitted through the LG Seller Lounge, the process is taking a lot longer than usual.
>It is processed sequentially according to the inflow order, but it may take some time for the QA results to come out.
>LG Seller Lounge is doing its best to ensure that your app is released A.S.A.P.
>
>We are always striving to provide the best service, so we ask for your understanding. If you have any further inquiries, please use 1:1 Inquiry.
> 
>Thank you.
>LG Seller Lounge
 
So as far as things go, we just have to keep waiting for now. I won't be sending in a 1:1 request for a status update since this makes it pretty clear.

If anything changes, I'll let you know.
- Anthony

**Comment by anthonylavado** [comment]
Sorry for not checking in sooner. LG let us know that they've also been doing some testing unrelated to webOS 5 (remember that note about next year's platform launch?). They found an item that we'll need to fix for that future version, but they're letting us defer that until later.

No other notes from them on the current release, still "processing".

**Comment by anthonylavado** [comment]
Just letting you all know it is still in the same stage with LG. We are at 55 days from October 1st submission at this time.

**Comment by anthonylavado** [comment]
Good news everyone! Finally after two months in "processing", the release is now available for webOS 5!

I'll make a bigger announcement soon, but this is your heads up to go and get it.

The version is listed as 1.1.2, but there are no code changes compared to what's on here at the moment. It should all be the same. I just had to use a new version number as part of the submission form.

**Comment by vtol79** [comment]
Hi, i disabled the dev mode on my tv to install jellyfin 1.1.2 and then realised that is only available for webos5 tvs from 2020!
Now i have to install the ipk again... hope this helps someone to avoid doing that too.

**Comment by TonoFilth** [comment]
Congratulations on the release!

Will it ever be available for pre-2020 WebOS 5 TVs at some point?

**Comment by Brice187** [comment]
Realized that to :( so webOS 5 != webOS 5

**Comment by vaind** [comment]
Yeah, I was wondering why I couldn't see it. Does anyone know what needs to be done? Maybe reopen this or should there be a followup issue?

**Comment by anthonylavado** [comment]
Okay, let me re-iterate something I've seen a few times.

LG has confusing software numbers. What you see as "Software Version" on your TV about screens isn't necessarily what version of webOS you have.

Software version is more like "Firmware Version" in this case. To check what version of webOS you have, LG recommends this:

>In LG Smart+ TV, go to Settings > Quick Settings > General > About this TV > webOS TV Version.

([source](https://webostv.developer.lge.com/faq/2016-10-25-general-how-check-platform-version-my-tv))

There's no real authoritative resource I have on this (if someone has a link, please comment it), but I believe that generally webOS 5.x is TV's from 2020 or newer.

I'm sorry if your model isn't covered yet - we are working to make it more widely available again, and if the two month delay on this from LG means anything, we've got an uphill battle.

We have some newly identified issues that they've given us a pass on for bow, but that they want fixed for the next update. On the next round, I want to go for broke and submit compatibility for all platforms, including upcoming 2023 TVs.

**Comment by vtol79** [comment]
Thanks for the explanation Anthony.
The software version is indeed not the same as the webos versions!

Are there any plans to get jellyfin into pre-webos 5 repos?

**Comment by Chuppaaa** [comment]
Hi,
I wanted to thank you for Jellyfin in WebOs5 in the LG store. I downloaded the application, checked it quickly and everything seems to work! Beautifully!
**5 star rating!**

The only thing that caught my eye was the inability to change the interface settings so that the assigned folders were on the vertical bar on the left side of the screen. At the moment they are horizontal on the main page but there is no way to change it to the sidebar. Can we count on adding this option in the next update?

One more note, the subtitle size option at the moment we have 5 sizes to choose from but the jump between them is too large would it be possible for the user to change the font size, e.g. to 20,22,24,26,28,30.. and similarly with changing the height of subtitles by the user?
I wanted to give a little bit up from the bottom bar to make it easier to read Polish characters, but the settings that are have too much difference in height and the only sensible setting so that the subtitles do not hit the image is the setting at the very bottom edge.

I look forward to the next version, great job!

**Comment by syncretized** [comment]
Working great - thank you for pushing through the process with LG to get this released!

**Comment by stegl** [comment]
Thanks for all your hard work to get it to here. 
Jellyfin just works sooooo much better.. Good job and thaaank you guys for this amazing app.

Sadly i dont have it yet on tv... Webos 05.60.20

Have a nice day everyone.

**Comment by Chuppaaa** [comment]
It's probably time to make an App for HISENSE 55U7QF now, the PLEX application has not been working on this TV for over a year
